import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16
