import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[keyboard]
bindings = [
  # Fix <C-6> on Neovim.
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
