import = [
  "~/.config/alacritty/tokyonight-storm.toml",
  "~/.config/alacritty-linux/linux.toml",
  "~/.config/alacritty-macos/macos.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 16

#normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
#bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
#italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
#size = 18

[keyboard]
bindings = [
  # Fix <C-6> on Neovim.
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
